openapi: 3.0.3
info:
  title: OpenLibrary Search (minimal)
  version: 1.0.0
servers:
  - url: https://openlibrary.org
paths:
  /search.json:
    get:
      operationId: searchBooks
      summary: Search OpenLibrary by title
      parameters:
        - in: query
          name: title
          required: true
          schema: { type: string }
          description: Title to search for
        - in: query
          name: page
          required: false
          schema: { type: integer, minimum: 1, default: 1 }
          description: Page number (1-based)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocsSearchResponse"
components:
  schemas:
    DocsSearchResponse:
      type: object
      properties:
        numFound: { type: integer }
        start: { type: integer }
        docs:
          type: array
          items:
            $ref: "#/components/schemas/Doc"
    Doc:
      type: object
      properties:
        key: { type: string }
        title: { type: string }
        author_name:
          type: array
          items: { type: string }
        first_publish_year: { type: integer }
        isbn:
          type: array
          items: { type: string }
        edition_count: { type: integer }
        language:
          type: array
          items: { type: string }